# project2

use the brain size data set and make classification with random forest.

In [1]:
import pandas as pd
import numpy as np
data= pd.read_csv('brain_size.csv', sep=";",na_values=('.'))
data

Unnamed: 0  Gender  FSIQ  VIQ  PIQ  Weight  Height  MRI_Count
0            1  Female   133  132  124   118.0    64.5     816932
1            2    Male   140  150  124     NaN    72.5    1001121
2            3    Male   139  123  150   143.0    73.3    1038437
3            4    Male   133  129  128   172.0    68.8     965353
4            5  Female   137  132  134   147.0    65.0     951545
5            6  Female    99   90  110   146.0    69.0     928799
6            7  Female   138  136  131   138.0    64.5     991305
7            8  Female    92   90   98   175.0    66.0     854258
8            9    Male    89   93   84   134.0    66.3     904858
9           10    Male   133  114  147   172.0    68.8     955466
10          11  Female   132  129  124   118.0    64.5     833868
11          12    Male   141  150  128   151.0    70.0    1079549
12          13    Male   135  129  124   155.0    69.0     924059
13          14  Female   140  120  147   155.0    70.5     856472
14          15  Female    96  100   90   146.0    66.0     878897
15          16  Female    83   71   96   135.0    68.0     865363
16          17  Female   132  132  120   127.0    68.5     852244
17          18    Male   100   96  102   178.0    73.5     945088
18          19  Female   101  112   84   136.0    66.3     808020
19          20    Male    80   77   86   180.0    70.0     889083
20          21    Male    83   83   86     NaN     NaN     892420
21          22    Male    97  107   84   186.0    76.5     905940
22          23  Female   135  129  134   122.0    62.0     790619
23          24    Male   139  145  128   132.0    68.0     955003
24          25  Female    91   86  102   114.0    63.0     831772
25          26    Male   141  145  131   171.0    72.0     935494
26          27  Female    85   90   84   140.0    68.0     798612
27          28    Male   103   96  110   187.0    77.0    1062462
28          29  Female    77   83   72   106.0    63.0     793549
29          30  Female   130  126  124   159.0    66.5     866662
30          31  Female   133  126  132   127.0    62.5     857782
31          32    Male   144  145  137   191.0    67.0     949589
32          33    Male   103   96  110   192.0    75.5     997925
33          34    Male    90   96   86   181.0    69.0     879987
34          35  Female    83   90   81   143.0    66.5     834344
35          36  Female   133  129  128   153.0    66.5     948066
36          37    Male   140  150  124   144.0    70.5     949395
37          38  Female    88   86   94   139.0    64.5     893983
38          39    Male    81   90   74   148.0    74.0     930016
39          40    Male    89   91   89   179.0    75.5     935863

In [2]:
data.describe()

Unnamed: 0        FSIQ         VIQ        PIQ      Weight     Height  \
count   40.000000   40.000000   40.000000   40.00000   38.000000  39.000000   
mean    20.500000  113.450000  112.350000  111.02500  151.052632  68.525641   
std     11.690452   24.082071   23.616107   22.47105   23.478509   3.994649   
min      1.000000   77.000000   71.000000   72.00000  106.000000  62.000000   
25%     10.750000   89.750000   90.000000   88.25000  135.250000  66.000000   
50%     20.500000  116.500000  113.000000  115.00000  146.500000  68.000000   
75%     30.250000  135.500000  129.750000  128.00000  172.000000  70.500000   
max     40.000000  144.000000  150.000000  150.00000  192.000000  77.000000   

          MRI_Count  
count  4.000000e+01  
mean   9.087550e+05  
std    7.228205e+04  
min    7.906190e+05  
25%    8.559185e+05  
50%    9.053990e+05  
75%    9.500780e+05  
max    1.079549e+06

In [3]:
data['Weight']=data['Weight'].fillna((data['Weight'].mean()))
data['Height']=data['Height'].fillna((data['Height'].mean()))
data


Unnamed: 0  Gender  FSIQ  VIQ  PIQ      Weight     Height  MRI_Count
0            1  Female   133  132  124  118.000000  64.500000     816932
1            2    Male   140  150  124  151.052632  72.500000    1001121
2            3    Male   139  123  150  143.000000  73.300000    1038437
3            4    Male   133  129  128  172.000000  68.800000     965353
4            5  Female   137  132  134  147.000000  65.000000     951545
5            6  Female    99   90  110  146.000000  69.000000     928799
6            7  Female   138  136  131  138.000000  64.500000     991305
7            8  Female    92   90   98  175.000000  66.000000     854258
8            9    Male    89   93   84  134.000000  66.300000     904858
9           10    Male   133  114  147  172.000000  68.800000     955466
10          11  Female   132  129  124  118.000000  64.500000     833868
11          12    Male   141  150  128  151.000000  70.000000    1079549
12          13    Male   135  129  124  155.000000  69.000000     924059
13          14  Female   140  120  147  155.000000  70.500000     856472
14          15  Female    96  100   90  146.000000  66.000000     878897
15          16  Female    83   71   96  135.000000  68.000000     865363
16          17  Female   132  132  120  127.000000  68.500000     852244
17          18    Male   100   96  102  178.000000  73.500000     945088
18          19  Female   101  112   84  136.000000  66.300000     808020
19          20    Male    80   77   86  180.000000  70.000000     889083
20          21    Male    83   83   86  151.052632  68.525641     892420
21          22    Male    97  107   84  186.000000  76.500000     905940
22          23  Female   135  129  134  122.000000  62.000000     790619
23          24    Male   139  145  128  132.000000  68.000000     955003
24          25  Female    91   86  102  114.000000  63.000000     831772
25          26    Male   141  145  131  171.000000  72.000000     935494
26          27  Female    85   90   84  140.000000  68.000000     798612
27          28    Male   103   96  110  187.000000  77.000000    1062462
28          29  Female    77   83   72  106.000000  63.000000     793549
29          30  Female   130  126  124  159.000000  66.500000     866662
30          31  Female   133  126  132  127.000000  62.500000     857782
31          32    Male   144  145  137  191.000000  67.000000     949589
32          33    Male   103   96  110  192.000000  75.500000     997925
33          34    Male    90   96   86  181.000000  69.000000     879987
34          35  Female    83   90   81  143.000000  66.500000     834344
35          36  Female   133  129  128  153.000000  66.500000     948066
36          37    Male   140  150  124  144.000000  70.500000     949395
37          38  Female    88   86   94  139.000000  64.500000     893983
38          39    Male    81   90   74  148.000000  74.000000     930016
39          40    Male    89   91   89  179.000000  75.500000     935863

# changing female and male to 0 and 1

In [4]:
Gender = {'Male': 1,'Female': 0}
data.Gender = [Gender[item] for item in data.Gender] 
print(data) 

    Unnamed: 0  Gender  FSIQ  VIQ  PIQ      Weight     Height  MRI_Count
0            1       0   133  132  124  118.000000  64.500000     816932
1            2       1   140  150  124  151.052632  72.500000    1001121
2            3       1   139  123  150  143.000000  73.300000    1038437
3            4       1   133  129  128  172.000000  68.800000     965353
4            5       0   137  132  134  147.000000  65.000000     951545
5            6       0    99   90  110  146.000000  69.000000     928799
6            7       0   138  136  131  138.000000  64.500000     991305
7            8       0    92   90   98  175.000000  66.000000     854258
8            9       1    89   93   84  134.000000  66.300000     904858
9           10       1   133  114  147  172.000000  68.800000     955466
10          11       0   132  129  124  118.000000  64.500000     833868
11          12       1   141  150  128  151.000000  70.000000    1079549
12          13       1   135  129  124  155.000000 

# Defining X and Y as label and features

In [5]:
(X1,y1)=data.iloc[:,3:],data['Gender']
print(X1)

    VIQ  PIQ      Weight     Height  MRI_Count
0   132  124  118.000000  64.500000     816932
1   150  124  151.052632  72.500000    1001121
2   123  150  143.000000  73.300000    1038437
3   129  128  172.000000  68.800000     965353
4   132  134  147.000000  65.000000     951545
5    90  110  146.000000  69.000000     928799
6   136  131  138.000000  64.500000     991305
7    90   98  175.000000  66.000000     854258
8    93   84  134.000000  66.300000     904858
9   114  147  172.000000  68.800000     955466
10  129  124  118.000000  64.500000     833868
11  150  128  151.000000  70.000000    1079549
12  129  124  155.000000  69.000000     924059
13  120  147  155.000000  70.500000     856472
14  100   90  146.000000  66.000000     878897
15   71   96  135.000000  68.000000     865363
16  132  120  127.000000  68.500000     852244
17   96  102  178.000000  73.500000     945088
18  112   84  136.000000  66.300000     808020
19   77   86  180.000000  70.000000     889083
20   83   86 

# Definig train and test

In [6]:
import pandas as pd
import sklearn
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X1, y1, test_size=0.33, random_state=0)

In [7]:
print(X_train)

    VIQ  PIQ      Weight  Height  MRI_Count
39   91   89  179.000000    75.5     935863
30  126  132  127.000000    62.5     857782
34   90   81  143.000000    66.5     834344
16  132  120  127.000000    68.5     852244
36  150  124  144.000000    70.5     949395
8    93   84  134.000000    66.3     904858
13  120  147  155.000000    70.5     856472
5    90  110  146.000000    69.0     928799
17   96  102  178.000000    73.5     945088
14  100   90  146.000000    66.0     878897
33   96   86  181.000000    69.0     879987
7    90   98  175.000000    66.0     854258
32   96  110  192.000000    75.5     997925
1   150  124  151.052632    72.5    1001121
26   90   84  140.000000    68.0     798612
12  129  124  155.000000    69.0     924059
31  145  137  191.000000    67.0     949589
24   86  102  114.000000    63.0     831772
6   136  131  138.000000    64.5     991305
23  145  128  132.000000    68.0     955003
21  107   84  186.000000    76.5     905940
19   77   86  180.000000    70.0

 Fitting random forest classification to data

In [8]:
from sklearn.ensemble import RandomForestClassifier
rf1 = RandomForestClassifier(random_state=0)
rf1.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

Checking model for test data

In [9]:
y1_pred = rf1.predict(X_test)
y1_pred

array([0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1], dtype=int64)

In [10]:
y_test

22    0
20    1
25    1
4     0
10    0
15    0
28    0
11    1
18    0
29    0
27    1
35    0
37    0
2     1
Name: Gender, dtype: int64

# Evaluating the Algorithm
For classification problems the metrics used to evaluate an algorithm are accuracy, confusion matrix, precision recall, and F1 values. Execute the following script to find these values:


In [11]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y1_pred))
print(classification_report(y_test,y1_pred))
print(accuracy_score(y_test, y1_pred))

[[8 1]
 [0 5]]
             precision    recall  f1-score   support

          0       1.00      0.89      0.94         9
          1       0.83      1.00      0.91         5

avg / total       0.94      0.93      0.93        14

0.928571428571


Interpreting the Confusion Matrix: 
    
Model predicted 8 female but actually its 9 female in test data so 1 is incorrect.
Model predicted 6 men.but its actually 5 men. 


In [15]:
evaluation=(13/14)*100
evaluation

92.85714285714286

# finding weight of features to show the importance of features.

In [17]:
featureweight = pd.DataFrame(rf1.feature_importances_, index=X_test.columns, columns=["Importance"])
print(featureweight.sort_values(['Importance']))

           Importance
VIQ          0.069410
PIQ          0.073819
Weight       0.206602
Height       0.236878
MRI_Count    0.413291


so its very nice to see the MRI_count feature has more impact to select the label of men for female.

In [18]:
rf2 = RandomForestClassifier(n_estimators=200, criterion="entropy", random_state=0)

In [20]:
rf2.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=200, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [21]:
y2_pred = rf2.predict(X_test)

In [22]:
cm_2 = confusion_matrix(y_test, y2_pred)
cm_2

array([[8, 1],
       [0, 5]], dtype=int64)

so no difference in this example for adding more parameters in random forest