## Exercise Answer
<br>
<div style="font-size:16px; line-height:25pt">
    <h3>Task 1.</h3>
    Without using numpy, create a <b>list that contains 20 random number in the range of 1 to 10</b>. Then <b>count how many 4 </b>does the list contains.
</div>

> **Hints:**
> 1. use ***list.count(x)***

In [10]:
import random
data = []
for i in range(20):
    data.append(random.randint(1,10))
    
print(data)
print(data.count(4))

[1, 4, 6, 1, 6, 5, 9, 2, 7, 6, 6, 8, 1, 8, 6, 8, 7, 5, 1, 3]
1


<div style="font-size:16px; line-height:25pt">
    <h3>Task 2.</h3>
    Use the list that you have created from the previous task, now, <b>arrange the elements inside the list in accending order</b>.
</div>

> **Hints:**
> 1. use ***list.sort()***

In [11]:
data.sort()
print(data)

[1, 1, 1, 1, 2, 3, 4, 5, 5, 6, 6, 6, 6, 6, 7, 7, 8, 8, 8, 9]


<div style="font-size:16px; line-height:25pt">
    <h3>Task 3.</h3>
    Without using numpy, create a <b>list that contains 30 random number in the range of 0 to 10</b>. From the list, <b>count how many 2 and 6</b> is contains inside the list.
</div>

In [15]:
import random
data1 = []
for i in range(30):
    data1.append(random.randint(0,10))
    
print(data1)

print(data1.count(2))
print(data1.count(6))

[9, 2, 7, 10, 1, 8, 8, 8, 8, 0, 9, 8, 7, 8, 10, 6, 5, 7, 6, 5, 7, 8, 8, 9, 0, 4, 5, 10, 2, 2]
3
2


<div style="font-size:16px; line-height:25pt">
    <h3>Task 4.</h3>
    Use the list that you have created from the previous task, now, <b>arrange the elements inside the list in descending order</b>.
</div>

> **Hints:**
> 1. use ***list.sort( reverse = False )***

In [17]:
data1.sort( reverse = True )
print(data1)

[10, 10, 10, 9, 9, 9, 8, 8, 8, 8, 8, 8, 8, 8, 7, 7, 7, 7, 6, 6, 5, 5, 5, 4, 2, 2, 2, 1, 0, 0]


<div style="font-size:16px; line-height:25pt">
    <h3>Task 5.</h3>
    Using numpy, create a <b>list that contains 20 random number in the range of 10 to 20</b>. Then <b>count how many 15 </b>does the list contains.
</div>

> **Hints:**
> 1. use ***numpy.count_nonzero( array == x_value )***

In [20]:
import numpy as np
data2 = np.random.randint(10,20,20)
print(data2)

print(np.count_nonzero(data2 == 15))

[15 13 10 14 18 15 19 14 11 14 16 19 12 17 19 17 11 17 12 18]
2


<div style="font-size:16px; line-height:25pt">
    <h3>Task 6.</h3>
    Use the list that you have created from the previous task, now, <b>arrange the elements inside the list</b>.
</div>

> **Hints:**
> 1. use ***numpy.sort(a, axis=-1, kind=None, order=None)***

In [21]:
print(np.sort(data2))

[10 11 11 12 12 13 14 14 14 15 15 16 17 17 17 18 18 19 19 19]


<div style="font-size:16px; line-height:25pt">
    <h3>Task 7.</h3>
    Using numpy, create a <b>list that contains 50 random number in the range of -10 to 10</b>. From the list, <b>count how many -5 and 5</b> is contains inside the list.
</div>

In [22]:
import numpy as np
data3 = np.random.randint(-10,10,50)
print(data3)

print(np.count_nonzero(data3 == -5))
print(np.count_nonzero(data3 == 5))

[ 6  2  8  6 -7 -4 -6  4 -4 -6 -1 -5  1  9  6  5  6  3  0  2 -5 -9 -9 -9
 -1  1  3 -5  9 -1  5 -2  7 -4 -9 -8  7  5  0  0 -7 -7  0 -2 -5  9  8  5
  8  0]
4
4


<div style="font-size:16px; line-height:25pt">
    <h3>Task 8.</h3>
    Use the list that you have created from the previous task, now, <b>arrange the elements inside the list</b>.
</div>

In [23]:
print(np.sort(data3))

[-9 -9 -9 -9 -8 -7 -7 -7 -6 -6 -5 -5 -5 -5 -4 -4 -4 -2 -2 -1 -1 -1  0  0
  0  0  0  1  1  2  2  3  3  4  5  5  5  5  6  6  6  6  7  7  8  8  8  9
  9  9]


<div style="font-size:16px; line-height:25pt">
    <h3>Task 9.</h3>
    Using numpy, create a list that contains 200 random numbers in the range of -20 to 20. Find
    <ol>
        <li>the <b>average</b> of the list</li>
        <li>the <b>differance</b> between the <b>largest number and the smallest number</b></li>
        <li>find <b>how many times 7</b> appears in the list and <b>find the total</b> of it</li>
    </ol>
</div>

> **Hints:**
> 1. use ***numpy.count_nonzero( array == x_value )*** and multiply it with x value

In [25]:
import numpy as np
data4 = np.random.randint(-20,20,200)
print(data4)

print(sum(data4) / len(data4))
print(max(data4) - min(data4))
print(np.count_nonzero( data4 == 7))
print(np.count_nonzero( data4 == 7)*7)

[ -1   5  11  -3  16  13   8   4 -15 -11 -17  -6   8   8   1  17   8 -14
  12   2  13 -18 -15   9  -4  -9 -12   3  -7  -8  -1  10   0  17  -3   5
 -17  11 -18   5 -18  -6  11  15  14  14 -11  16 -11  19 -11  16 -19  -5
  17 -16  -6  15  10  -5 -17  16   3  -1 -11  -3   9 -11   3 -19 -12   3
 -11 -17  15  17   8   8   8  18  17  -6  16   9   0   2  -2  18  -7   9
  -4   4  19  -4  -8  16  18  11  16  15   0 -20  -5  10  -6  -3  17  19
   3 -14 -17  19   9 -12  10  -8  19 -16  14   0  -7   2   7  -8 -11  -1
  18  -9  13 -12   9 -20   7  -4  18  16   9  16  10  18  -8  14   9   3
  -7   5 -13  -7   9  11 -10  -4  12   8  -3  -5   0 -17   3  19  18   9
   2   6  11   6 -17  -7 -17   1   8  -6  17 -19  -1  -7   5  -7  -4   3
 -16   0  12  -4   3   1   6 -12   8 -13  -4   4  -6  -8 -10   3  16 -17
  13  13]
1.45
39
2
14


<div style="font-size:16px; line-height:25pt">
    <h3>Task 10.</h3>
    Use numpy<br>
    Below shows a list that contains 20 random number in the range(10, 20). Do:
    <ol>
        <li><b>add more elements</b> into the list that will make up the list to have <b>500 elements</b>. Set the <b>range</b> of elements in the list to <b>(-30, 30)</b></li>
        <li>find <b>how many times 21</b> appears in the list</li>
        <li><b>arrange the list</b></li>
    </ol>
</div>

In [38]:
import numpy as np
data5 = np.random.randint(10,20,20)
print(data5)

data5 = np.append(data5, [np.random.randint(-30,30,480)])
print(data5,'\n')

print(np.count_nonzero(data5 == 21),'\n')
print(np.sort(data5))

[18 17 12 18 15 12 14 13 11 18 18 14 16 17 13 19 12 14 15 15]
[ 18  17  12  18  15  12  14  13  11  18  18  14  16  17  13  19  12  14
  15  15 -28 -19  27 -28  17 -15   2   5 -24 -29  29  -2   3   0 -20  14
   7  -3 -16 -29   5 -13   6 -11  19 -22  29 -23 -22  -9  -9   1 -30 -10
 -21 -13  13  18 -25 -17  29  -7  16  22  -1  22  -8 -20 -26  10   0  20
  16 -13  21 -25 -17 -27   3  26  -3 -17  18 -15  15   5  -9 -11  -6  28
 -12  -9  26  16  19  29  -4 -11  25 -28  25 -10 -14   4  -9   2 -22  15
 -12  -1   0   0  -7  -7   5 -12   1   8   2  18   9  -3  22  -7 -16  18
  19  27 -27  15 -26  -4   3 -14  23 -27  28 -12 -13 -24  13 -29  -6  24
 -16   6  -8  10 -23 -13 -14 -22   8 -18 -18  26 -27   6 -30 -25 -26  18
   6  14  21  -3  27  21  -7  12 -18  23   3 -14 -22  21  19  13 -30   1
 -22  -7   6 -29  14  28  12  27 -14 -22 -24 -16 -28  20   7   1 -24 -28
 -12 -24  22  17 -25  22  22   5  24   8  20   5 -12  17 -28  28  -7  21
  25   5 -17  14  -8  28  11  17  27   5  -9  11 -14  11  18  